#!/usr/bin/env node
/*
  Regenerate `fonts-embedded.css` — the JK brand fonts (Source Serif 4, IBM Plex
  Sans, IBM Plex Mono) as Latin-subset woff2 embedded as data URIs.

  Why this exists: rendered brand artifacts (SOP renders, reports, one-off
  branded HTML) must be SELF-CONTAINED — the Artifact CSP and offline / Drive /
  print contexts all block external font requests. Embedding the faces as data
  URIs makes any HTML that includes this file render identically everywhere.

  This is a MAINTENANCE script — you only re-run it to add a weight/subset or
  refresh the faces. The committed `fonts-embedded.css` is the artifact everyone
  actually uses; you do not need this script to build a render.

  Usage:  node brand/design-system/fetch-fonts.mjs
  (Latin subset only. Add families/weights in `cssUrl` below if the system grows.)
*/
import { writeFileSync } from 'node:fs';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Weights match DESIGN.md: Source Serif 4 400/600 + 400 italic; Plex Sans 400/500/600; Plex Mono 400/500/600.
const cssUrl = 'https://fonts.googleapis.com/css2?' +
  'family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400' +
  '&family=IBM+Plex+Sans:wght@400;500;600' +
  '&family=IBM+Plex+Mono:wght@400;500;600' +
  '&display=swap';

const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } });
if (!res.ok) { console.error('CSS fetch failed', res.status); process.exit(1); }
const css = await res.text();

const blocks = css.split('/*').slice(1).map(s => '/*' + s);
let out = '/* JK brand fonts — Latin subset, embedded woff2 (self-contained).\n' +
          '   Generated by fetch-fonts.mjs. Include in any branded HTML render so it\n' +
          '   works offline, in Drive, when printed, and inside a CSP-restricted Artifact. */\n';
let kept = 0;
for (const b of blocks) {
  const subset = (b.match(/\/\*\s*([a-z0-9-]+)\s*\*\//i) || [])[1] || '';
  if (subset !== 'latin') continue;                       // Latin only keeps the file lean
  const woffUrl = (b.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  if (!woffUrl) continue;
  const wr = await fetch(woffUrl, { headers: { 'User-Agent': UA } });
  if (!wr.ok) { console.error('woff2 fetch failed', wr.status, woffUrl); continue; }
  const b64 = Buffer.from(await wr.arrayBuffer()).toString('base64');
  out += b.replace(/\/\*[^*]*\*\/\s*/, '')
          .replace(/url\(https:\/\/[^)]+\.woff2\)\s*format\('woff2'\)/,
                   `url(data:font/woff2;base64,${b64}) format('woff2')`).trim() + '\n';
  kept++;
  const fam = (b.match(/font-family:\s*'([^']+)'/) || [])[1];
  const wt = (b.match(/font-weight:\s*(\d+)/) || [])[1];
  const st = (b.match(/font-style:\s*(\w+)/) || [])[1];
  console.error(`embedded ${fam} ${wt} ${st}`);
}
writeFileSync(new URL('./fonts-embedded.css', import.meta.url), out);
console.error(`\nDone: ${kept} faces, ${(out.length/1024).toFixed(0)}KB → fonts-embedded.css`);
